### ISSUE TITLE
Question - list of terminals using libtickit?

### ISSUE THREAD

**Issue by marcotrosi** [leonerd/libtickit#2]
Hello Paul,

do you know by any chance if there is a terminal emulator project that uses libtickit?

thanks

--marco

**Comment by leonerd** [comment]
> do you know by any chance if there is a terminal emulator project that uses libtickit?
I would imagine not. libtickit is a library for terminal-based applications - such as text editors, IRC clients, whatever.. You wouldn't use it to implement a terminal emulator. That's the other side.

However, I also write libvterm, a library for implementing terminal emulators. Several are written using it; including my own pangoterm.

**Comment by marcotrosi** [comment]
> > do you know by any chance if there is a terminal emulator project that uses libtickit?
> > I would imagine not. libtickit is a library for terminal-based applications - such as text editors, IRC clients, whatever.. You wouldn't use it to implement a terminal emulator. That's the other side.
> 
> However, I also write libvterm, a library for implementing terminal emulators. Several are written using it; including my own pangoterm.

thanks
